# Generated by Django 4.2.6 on 2023-10-09 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ItemName', models.CharField(max_length=255)),
                ('ItemCode', models.CharField(max_length=255)),
                ('SKU', models.CharField(max_length=255)),
                ('ReferalCode', models.CharField(max_length=255)),
            ],
        ),
    ]
