# Generated by Django 4.2.6 on 2023-10-09 11:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='ReferalCode',
            new_name='ReferralCode',
        ),
    ]
